name: Vercel Deploy
description: Deploy app to Vercel

inputs:
  vercel-token:
    description: Vercel token
    required: true
  vercel-org-id:
    description: Vercel organization ID
    required: true
  vercel-project-id:
    description: Vercel project ID
    required: true
  environment-variables:
    description: Vercel environment variables, one KEY=value pair per line
    required: false
    default: ''
  sensitive-environment-variables:
    description: Vercel sensitive environment variables, one KEY=value pair per line
    required: false
    default: ''

outputs:
  url:
    description: Deployment URL
    value: ${{ steps.deployment.outputs.url }}

runs:
  using: composite

  steps:
    - name: Install Vercel CLI
      shell: bash
      run: pnpm install --global vercel@latest

    - name: Sync Vercel Environment Variables
      uses: ./.github/actions/vercel-env-sync
      with:
        vercel-token: ${{ inputs.vercel-token }}
        vercel-org-id: ${{ inputs.vercel-org-id }}
        vercel-project-id: ${{ inputs.vercel-project-id }}
        environment-variables: ${{ inputs.environment-variables }}
        sensitive-environment-variables: ${{ inputs.sensitive-environment-variables }}

    - name: Pull Vercel Environment Information
      shell: bash
      run: vercel pull --yes --environment=production --token="${{ inputs.vercel-token }}"
      env:
        VERCEL_ORG_ID: ${{ inputs.vercel-org-id }}
        VERCEL_PROJECT_ID: ${{ inputs.vercel-project-id }}

    - name: Build Project Artifacts
      shell: bash
      run: vercel build --prod --token="${{ inputs.vercel-token }}"
      env:
        VERCEL_ORG_ID: ${{ inputs.vercel-org-id }}
        VERCEL_PROJECT_ID: ${{ inputs.vercel-project-id }}

    - name: Deploy Project Artifacts to Vercel
      id: deployment
      shell: bash
      run: |
        DEPLOYMENT_URL="$(vercel deploy --prebuilt --prod --yes --token="${{ inputs.vercel-token }}")"
        echo "url=$DEPLOYMENT_URL" >> "$GITHUB_OUTPUT"
      env:
        VERCEL_ORG_ID: ${{ inputs.vercel-org-id }}
        VERCEL_PROJECT_ID: ${{ inputs.vercel-project-id }}
