/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: extract.json
export type MathBlock = {
  _type: 'mathBlock';
  latex?: string;
  displayMode?: boolean;
};

export type CodeBlock = {
  _type: 'codeBlock';
  language?: 'csharp' | 'typescript' | 'tsx' | 'python' | 'yaml' | 'txt';
  code?: string;
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: 'reference';
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
};

export type CategoryReference = {
  _ref: string;
  _type: 'reference';
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: 'category';
};

export type Post = {
  _id: string;
  _type: 'post';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  publishedAt?: string;
  updatedAt?: string;
  excerpt?: string;
  coverImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: 'image';
  };
  category?: CategoryReference;
  tags?: Array<string>;
  body?: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: 'span';
          _key: string;
        }>;
        style?: 'normal' | 'h2' | 'h3';
        listItem?: 'bullet' | 'number';
        markDefs?: Array<{
          href?: string;
          _type: 'link';
          _key: string;
        }>;
        level?: number;
        _type: 'block';
        _key: string;
      }
    | ({
        _key: string;
      } & CodeBlock)
    | ({
        _key: string;
      } & MathBlock)
    | {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        alt?: string;
        _type: 'image';
        _key: string;
      }
  >;
};

export type SanityImageCrop = {
  _type: 'sanity.imageCrop';
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: 'sanity.imageHotspot';
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type Category = {
  _id: string;
  _type: 'category';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  description?: string;
};

export type Slug = {
  _type: 'slug';
  current?: string;
  source?: string;
};

export type SanityImagePaletteSwatch = {
  _type: 'sanity.imagePaletteSwatch';
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: 'sanity.imagePalette';
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: 'sanity.imageDimensions';
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: 'sanity.imageMetadata';
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: 'sanity.fileAsset';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: 'sanity.assetSourceData';
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: 'sanity.imageAsset';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: 'geopoint';
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | MathBlock
  | CodeBlock
  | SanityImageAssetReference
  | CategoryReference
  | Post
  | SanityImageCrop
  | SanityImageHotspot
  | Category
  | Slug
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: ../../packages/sanity-blog/src/queries.ts
// Variable: postsQuery
// Query: *[_type == "post"] | order(publishedAt desc) {    _id,    title,    "slug": slug.current,    publishedAt,    updatedAt,    excerpt,    coverImage,    category->{      _id,      title,      "slug": slug.current    },    tags  }
export type PostsQueryResult = Array<{
  _id: string;
  title: string | null;
  slug: string | null;
  publishedAt: string | null;
  updatedAt: string | null;
  excerpt: string | null;
  coverImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: 'image';
  } | null;
  category: {
    _id: string;
    title: string | null;
    slug: string | null;
  } | null;
  tags: Array<string> | null;
}>;

// Source: ../../packages/sanity-blog/src/queries.ts
// Variable: postBySlugQuery
// Query: *[_type == "post" && slug.current == $slug][0] {    _id,    title,    "slug": slug.current,    publishedAt,    updatedAt,    excerpt,    coverImage,    "coverImageLqip": coverImage.asset->metadata.lqip,    "coverImageDimensions": coverImage.asset->metadata.dimensions{      width,      height,      aspectRatio    },    category->{      _id,      title,      "slug": slug.current    },    tags,    body[]{      ...,      _type == "image" => {        ...,        "lqip": asset->metadata.lqip,        "dimensions": asset->metadata.dimensions{          width,          height,          aspectRatio        }      }    }  }
export type PostBySlugQueryResult = {
  _id: string;
  title: string | null;
  slug: string | null;
  publishedAt: string | null;
  updatedAt: string | null;
  excerpt: string | null;
  coverImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: 'image';
  } | null;
  coverImageLqip: string | null;
  coverImageDimensions: {
    width: number | null;
    height: number | null;
    aspectRatio: number | null;
  } | null;
  category: {
    _id: string;
    title: string | null;
    slug: string | null;
  } | null;
  tags: Array<string> | null;
  body: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: 'span';
          _key: string;
        }>;
        style?: 'h2' | 'h3' | 'normal';
        listItem?: 'bullet' | 'number';
        markDefs?: Array<{
          href?: string;
          _type: 'link';
          _key: string;
        }>;
        level?: number;
        _type: 'block';
        _key: string;
      }
    | {
        _key: string;
        _type: 'codeBlock';
        language?: 'csharp' | 'python' | 'tsx' | 'txt' | 'typescript' | 'yaml';
        code?: string;
      }
    | {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        alt?: string;
        _type: 'image';
        _key: string;
        lqip: string | null;
        dimensions: {
          width: number | null;
          height: number | null;
          aspectRatio: number | null;
        } | null;
      }
    | {
        _key: string;
        _type: 'mathBlock';
        latex?: string;
        displayMode?: boolean;
      }
  > | null;
} | null;

// Source: ../../packages/sanity-blog/src/queries.ts
// Variable: categoryBySlugQuery
// Query: *[_type == "category" && slug.current == $slug][0] {    _id,    title,    "slug": slug.current,    description  }
export type CategoryBySlugQueryResult = {
  _id: string;
  title: string | null;
  slug: string | null;
  description: string | null;
} | null;

// Source: ../../packages/sanity-blog/src/queries.ts
// Variable: postsByCategoryQuery
// Query: *[_type == "post" && category->slug.current == $slug] | order(publishedAt desc) {    _id,    title,    "slug": slug.current,    publishedAt,    updatedAt,    excerpt,    coverImage,    category->{      _id,      title,      "slug": slug.current    },    tags  }
export type PostsByCategoryQueryResult = Array<{
  _id: string;
  title: string | null;
  slug: string | null;
  publishedAt: string | null;
  updatedAt: string | null;
  excerpt: string | null;
  coverImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: 'image';
  } | null;
  category: {
    _id: string;
    title: string | null;
    slug: string | null;
  } | null;
  tags: Array<string> | null;
}>;

// Source: ../../packages/sanity-blog/src/queries.ts
// Variable: postsByTagQuery
// Query: *[_type == "post" && $tag in tags] | order(publishedAt desc) {    _id,    title,    "slug": slug.current,    publishedAt,    updatedAt,    excerpt,    coverImage,    category->{      _id,      title,      "slug": slug.current    },    tags  }
export type PostsByTagQueryResult = Array<{
  _id: string;
  title: string | null;
  slug: string | null;
  publishedAt: string | null;
  updatedAt: string | null;
  excerpt: string | null;
  coverImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: 'image';
  } | null;
  category: {
    _id: string;
    title: string | null;
    slug: string | null;
  } | null;
  tags: Array<string> | null;
}>;

// Source: ../../packages/sanity-blog/src/queries.ts
// Variable: categoriesQuery
// Query: *[_type == "category"] | order(title asc) {    _id,    title,    "slug": slug.current  }
export type CategoriesQueryResult = Array<{
  _id: string;
  title: string | null;
  slug: string | null;
}>;

// Query TypeMap
import '@sanity/client';
declare module '@sanity/client' {
  interface SanityQueries {
    '\n  *[_type == "post"] | order(publishedAt desc) {\n    _id,\n    title,\n    "slug": slug.current,\n    publishedAt,\n    updatedAt,\n    excerpt,\n    coverImage,\n    category->{\n      _id,\n      title,\n      "slug": slug.current\n    },\n    tags\n  }\n': PostsQueryResult;
    '\n  *[_type == "post" && slug.current == $slug][0] {\n    _id,\n    title,\n    "slug": slug.current,\n    publishedAt,\n    updatedAt,\n    excerpt,\n    coverImage,\n    "coverImageLqip": coverImage.asset->metadata.lqip,\n    "coverImageDimensions": coverImage.asset->metadata.dimensions{\n      width,\n      height,\n      aspectRatio\n    },\n    category->{\n      _id,\n      title,\n      "slug": slug.current\n    },\n    tags,\n    body[]{\n      ...,\n      _type == "image" => {\n        ...,\n        "lqip": asset->metadata.lqip,\n        "dimensions": asset->metadata.dimensions{\n          width,\n          height,\n          aspectRatio\n        }\n      }\n    }\n  }\n': PostBySlugQueryResult;
    '\n  *[_type == "category" && slug.current == $slug][0] {\n    _id,\n    title,\n    "slug": slug.current,\n    description\n  }\n': CategoryBySlugQueryResult;
    '\n  *[_type == "post" && category->slug.current == $slug] | order(publishedAt desc) {\n    _id,\n    title,\n    "slug": slug.current,\n    publishedAt,\n    updatedAt,\n    excerpt,\n    coverImage,\n    category->{\n      _id,\n      title,\n      "slug": slug.current\n    },\n    tags\n  }\n': PostsByCategoryQueryResult;
    '\n  *[_type == "post" && $tag in tags] | order(publishedAt desc) {\n    _id,\n    title,\n    "slug": slug.current,\n    publishedAt,\n    updatedAt,\n    excerpt,\n    coverImage,\n    category->{\n      _id,\n      title,\n      "slug": slug.current\n    },\n    tags\n  }\n': PostsByTagQueryResult;
    '\n  *[_type == "category"] | order(title asc) {\n    _id,\n    title,\n    "slug": slug.current\n  }\n': CategoriesQueryResult;
  }
}
