name: Deploy Blog

on:
  push:
    branches:
      - main
    paths:
      - apps/blog/**
      - packages/hooks/**
      - packages/sanity-blog/**
      - packages/search-blog/**
      - .github/actions/vercel-deploy/**
      - .github/workflows/deploy-blog.yml

  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: blog-vercel
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    environment:
      name: blog-vercel
      url: ${{ steps.deployment.outputs.url }}

    env:
      SANITY_PROJECT_ID: ${{ secrets.STUDIO_BLOG_PROJECT_ID }}
      SANITY_DATASET: ${{ secrets.STUDIO_DATASET }}
      SANITY_API_VERSION: 2026-01-12

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Node.js + pnpm
        uses: ./.github/actions/setup-node-pnpm
        with:
          node-version: 24

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Lint
        run: pnpm lint --filter blog

      - name: Typecheck
        run: pnpm check-types --filter blog

      - name: Deploy Blog to Vercel
        id: deployment
        uses: ./.github/actions/vercel-deploy
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
